server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/base
    username: postgres
    password: postgres
  mail:
    host: smtp.foo.bar
    port: 587
    username: noreply@foobar.es
    password: changeme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: base
#        format_sql: true
        #       This property implies a new transaction and DB connection per each lazy load after a call to a JPARepository
#        Consider using eager loading when needed to avoid n+1 problem
        enable_lazy_load_no_trans: true
#    show-sql: true

    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs

security:
  jwt:
    jwtSecret: TheDefinitiveSecret
    jwtExpirationMs: 300000
    jwtRefreshExpirationMs: 1800000
    sessionDurationMs: 36000000
    jwtIssuerName: cpinedo.es
  userMaxLength: 100
  userMinLength: 4
  passwordMaxLength: 50
  passwordMinLength: 3
  customLimits: true
  google:
    clientIds: >
      example.client.foo,
      example.client.bar

logging:
  level:
    root: ERROR
    org:
      flywaydb: INFO
